### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by gcutrini** [raDiesle/backbone.js-jquerymobile-boilerplate-template#1]
Cannot run boilerplate.

I think there is something wrong in the handlebars build.
In handlebar_packaged.js I get:
this['JST']['app/templates/basic/template_basic_page_simple.handlebars']
and should be getting this['JST']['template_basic_page_simple']

Also, grunt debug build fails while running "requirejs:mainConfigFile" (requirejs) task

> > Error: Missing either an "out" or "dir" config value. If using "appDir" for a
> > full project optimization, use "dir". If you want to optimize to one file,
> > use "out".

Any clue?

**Comment by raDiesle** [comment]
Hi,

1.
You are absolutetly right!
see here : https://github.com/gruntjs/grunt-contrib/pull/97

There will be a new version with a new feature on monday of the handlebars.js grunt task.
Currently, using partials was not possible.
There will be a new properties/function called processName in the handlebars grunt task which can be used like:

processName : function(srcFile){
  var fileName = filepath.substring(filepath.lastIndexOf('/')+1);
  return fileName.substring(0, fileName.indexOf('.'));
}

If you want to make it running in the current version, 
You'll need to replace/insert in your project in node_modules/grunt-contrib/tasks/handlebars.js at the bottom

var fileName = filepath.substring(filepath.lastIndexOf('/')+1);
return namespace + "['" + fileName.substring(0, fileName.indexOf('.'))+ "'] = " + output;
1. 
   What do you mean by build fails?
   By running bbb require.js ?

Thanks for the info!

**Comment by gcutrini** [comment]
1. Thanks for the handlebars grunt task (temporary) fix.
2. Exactly that, the bbb require.js task fails with the attached output. I see the same issue has now been reported on the backbone-boilerplate project https://github.com/tbranyen/backbone-boilerplate/issues/135 .

**Comment by gcutrini** [comment]
Fixed with commit https://github.com/raDiesle/backbone.js-jquerymobile-boilerplate-template/commit/40e71d70b2576824268385066b557bfaeefb3f2c
