### ISSUE TITLE
grunt release

### ISSUE THREAD

**Issue by kingnight** [raDiesle/backbone.js-jquerymobile-boilerplate-template#10]
in Gruntfile the task:
<code>grunt.registerTask("release", ["clean", "handlebars", "requirejs", "concat", "copy"]);</code>
when "requirejs" task completed, all requeired libs and app combined to /dist/debug/require.js,
but in "concat" and "copy" task all dependent libs are also copy to release folder, in index.html files :
<code> script data-main="/app/config" src="/assets/js/libs/require.js"    </code>
 also repeatly require every libs ,what 's why ? why not only need require.js file?

**Comment by raDiesle** [comment]
Hi kingnight,

You are right,
current state makes no sense at all.

I am waiting for the bbb release task to be working with the current 0.40 grunt version.
Later on, I'm planning to clean the grunt setup.
If you like to, feel free to commit an alternative setup.

Thank you,

**Comment by kingnight** [comment]
thank you too ,i learned a lot from this template
